ALTER TABLE tb_user ADD COLUMN IF NOT EXISTS street VARCHAR(255);
ALTER TABLE tb_user ADD COLUMN IF NOT EXISTS number VARCHAR(50);
ALTER TABLE tb_user ADD COLUMN IF NOT EXISTS complement VARCHAR(255);
ALTER TABLE tb_user ADD COLUMN IF NOT EXISTS neighborhood VARCHAR(255);
ALTER TABLE tb_user ADD COLUMN IF NOT EXISTS city VARCHAR(255);
ALTER TABLE tb_user ADD COLUMN IF NOT EXISTS state VARCHAR(2);
ALTER TABLE tb_user ADD COLUMN IF NOT EXISTS zip_code VARCHAR(20);
ALTER TABLE tb_user ADD COLUMN IF NOT EXISTS balance DOUBLE PRECISION DEFAULT 1800;

UPDATE tb_user SET balance = 1800 WHERE balance IS NULL;
