spring.application.name=config-service
server.port=8888

#spring.profiles.active=native

#spring.cloud.config.server.native.search-locations=classpath:/configs/{application}

spring.cloud.config.server.git.uri=https://github.com/Brunog21/ExtraG1Microservices.git
spring.cloud.config.server.git.search-paths=configs/{application}
spring.cloud.config.server.git.default-label=main

#Self Registration Pattern
eureka.client.service-url.default-zone=http://localhost:8761/eureka
#Ideal para ambiente containerizados
eureka.instance.prefer-ip-address=true
#Personalizar o id de cada instância
eureka.instance.instance-id=${spring.application.name}:${server.port}
#Indicar que o Service Registry deve validar a saúde do serviço através do actuator, e não somente Heartbeat
# Opcional - Valor Default = TRUE
eureka.client.healthcheck.enabled=true

#Configuração mínima para atuação com o Service Registry de forma consciente
management.endpoints.web.exposure.include=health,info,metrics
#ATENÇÃO: Cuidado a expor esses dados
#Exibir todas as informações de saúde da aplicação
management.endpoint.health.show-details=always
#Exibir informações no endpoint /actuator/info
management.info.env.enabled=true

#Personalização de ifnormações do endpoint /actuator/info
info.app.name=${spring.application.name}
info.app.description=Servidor centralizado de configura��es
info.app.autor=Bruno Galvagni
#Personalização de Metadatas para o Eureka Service Registry
eureka.instance.metadata-map.github.repo=https://github.com/Brunog21/ExtraG1Microservices.git

#Definir a ulização das Probes Liveness e Readiness + exibição de de informações de componentes diversos
# Opcional: Padrão já é TRUE
management.endpoint.health.probes.enabled=true
management.health.defaults.enabled=true